export const FIELD_LIMITS = {
  email: 254,
  passwordMin: 8,
  passwordMax: 72,
  fullName: 100,
  phoneDigits: 15,
  vehicleNumber: 20,
  companyName: 120,
  location: 120,
  source: 100,
  notes: 500,
  remarks: 500,
  comments: 500,
  address: 250,
  search: 100,
  gstin: 15,
  vehicleCapacity: 40,
  creditDaysDigits: 3,
  creditLimitDigits: 12,
  currencyDigits: 12,
  distanceDigits: 6,
  percentDigits: 5,
  mileageIntegerDigits: 2,
  mileageFractionDigits: 2,
  weightIntegerDigits: 5,
  weightFractionDigits: 2,
} as const;
